name: kpa_shift_app
description: "KPA Shift & Attendance Tracker App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  shared_preferences_android: 2.3.4
  path_provider_android: 2.2.15

flutter:
  uses-material-design: true
